// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZivotopisCore.Data;

#nullable disable

namespace ZivotopisCore.Migrations
{
    [DbContext(typeof(AplikaciaDbContext))]
    [Migration("20251104133913_AddPriezviskoToPacient")]
    partial class AddPriezviskoToPacient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiagnozaModelPacientModel", b =>
                {
                    b.Property<int>("DiagnozyId")
                        .HasColumnType("int");

                    b.Property<int>("PacientiId")
                        .HasColumnType("int");

                    b.HasKey("DiagnozyId", "PacientiId");

                    b.HasIndex("PacientiId");

                    b.ToTable("DiagnozaModelPacientModel");
                });

            modelBuilder.Entity("ZivotopisCore.Models.DiagnozaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Popis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiagnozaModel");
                });

            modelBuilder.Entity("ZivotopisCore.Models.GenetickeVysetrenieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumVysetrenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacientModelId")
                        .HasColumnType("int");

                    b.Property<string>("Vysledok")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PacientModelId");

                    b.ToTable("Vysetrenia");
                });

            modelBuilder.Entity("ZivotopisCore.Models.PacientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Meno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pohlavie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezvisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodneCislo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pacienti");
                });

            modelBuilder.Entity("ZivotopisCore.Models.PriznakModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumZaznamenania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacientModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacientModelId");

                    b.ToTable("Priznaky");
                });

            modelBuilder.Entity("DiagnozaModelPacientModel", b =>
                {
                    b.HasOne("ZivotopisCore.Models.DiagnozaModel", null)
                        .WithMany()
                        .HasForeignKey("DiagnozyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZivotopisCore.Models.PacientModel", null)
                        .WithMany()
                        .HasForeignKey("PacientiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZivotopisCore.Models.GenetickeVysetrenieModel", b =>
                {
                    b.HasOne("ZivotopisCore.Models.PacientModel", "Pacient")
                        .WithMany("GenetickeVysetrenia")
                        .HasForeignKey("PacientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ZivotopisCore.Models.PriznakModel", b =>
                {
                    b.HasOne("ZivotopisCore.Models.PacientModel", "Pacient")
                        .WithMany("Priznaky")
                        .HasForeignKey("PacientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ZivotopisCore.Models.PacientModel", b =>
                {
                    b.Navigation("GenetickeVysetrenia");

                    b.Navigation("Priznaky");
                });
#pragma warning restore 612, 618
        }
    }
}
