// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZivotopisCore.Data;

#nullable disable

namespace ZivotopisCore.Migrations
{
    [DbContext(typeof(AplikaciaDbContext))]
    partial class AplikaciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiagnozaModelPacientModel", b =>
                {
                    b.Property<int>("DiagnozyId")
                        .HasColumnType("integer");

                    b.Property<int>("PacientiId")
                        .HasColumnType("integer");

                    b.HasKey("DiagnozyId", "PacientiId");

                    b.HasIndex("PacientiId");

                    b.ToTable("DiagnozaModelPacientModel", (string)null);
                });

            modelBuilder.Entity("ZivotopisCore.Models.DiagnozaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivna")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DatumVytvorenia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Popis")
                        .HasColumnType("text");

                    b.Property<string>("Typ")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Diagnozy");
                });

            modelBuilder.Entity("ZivotopisCore.Models.GenetickeVysetrenieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumVysetrenia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacientModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Vysledok")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PacientModelId");

                    b.ToTable("Vysetrenia");
                });

            modelBuilder.Entity("ZivotopisCore.Models.PacientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archivovany")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DatumNarodenia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Meno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pohlavie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priezvisko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RodneCislo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pacienti");
                });

            modelBuilder.Entity("ZivotopisCore.Models.PriznakModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumZaznamenania")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacientModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacientModelId");

                    b.ToTable("Priznaky");
                });

            modelBuilder.Entity("DiagnozaModelPacientModel", b =>
                {
                    b.HasOne("ZivotopisCore.Models.DiagnozaModel", null)
                        .WithMany()
                        .HasForeignKey("DiagnozyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZivotopisCore.Models.PacientModel", null)
                        .WithMany()
                        .HasForeignKey("PacientiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZivotopisCore.Models.GenetickeVysetrenieModel", b =>
                {
                    b.HasOne("ZivotopisCore.Models.PacientModel", "Pacient")
                        .WithMany("GenetickeVysetrenia")
                        .HasForeignKey("PacientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ZivotopisCore.Models.PriznakModel", b =>
                {
                    b.HasOne("ZivotopisCore.Models.PacientModel", "Pacient")
                        .WithMany("Priznaky")
                        .HasForeignKey("PacientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("ZivotopisCore.Models.PacientModel", b =>
                {
                    b.Navigation("GenetickeVysetrenia");

                    b.Navigation("Priznaky");
                });
#pragma warning restore 612, 618
        }
    }
}
